version: "2"
services:
  pgsql:
    image: mdillon/postgis:latest
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/database:/var/lib/postgresql/data